name: Update Gradle Wrapper

on:
  schedule:
    # every day at 2am
    - cron: "23 30 * * *"

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v2
        with:
          release-channel: release-candidate
