name: Update Gradle Wrapper

on:
  workflow_dispatch:
  schedule:
    # "weekly" https://crontab.guru/every-week
    - cron: "0 0 * * 0"

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17
          cache: 'gradle'
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          #paths: */**
          #paths-ignore: sub-project/examples/**
          #labels: dependencies
      - uses: gradle/actions/wrapper-validation@v4
